### ISSUE TITLE
Prepare for .NET 8

### ISSUE THREAD

**Issue by seesharprun** [Azure-Samples/cosmos-db-design-patterns#13]
We have a few things to track as we prepare for .NET 8:

- [ ] Check projects work as-is with an in place ugprade to .NET 8
- [ ] Upgrade base devcontainer image to .NET 8
- [ ] Update dependencies to latest stable
- [ ] Use solution files consistently

**Comment by seesharprun** [comment]
Regarding the solution files, the [C# DevKit extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit) automatically generates them. It would be ideal to already have them in-place with consistent namespaces.

**Comment by seesharprun** [comment]
🦖 Punting to November

**Comment by markjbrown** [comment]
projects updated to .NET 8
