### ISSUE TITLE
Attribute Array: sample query change

### ISSUE THREAD

**Issue by tsubakimoto** [Azure-Samples/cosmos-db-design-patterns#19]
Hi team,

The JSON in the sample below does not allow us to get the size value we want to SELECT in the query.

https://github.com/Azure-Samples/cosmos-db-design-patterns/blob/242a27fdc79a02f1bfbcfba2202c3c305b5004a6/attribute-array/README.md?plain=1#L98-L128

Query result (could not include `s.site`)

```json
[
    {
        "name": "Practical Metal Sausages",
        "count": 96
    },
    {
        "name": "Practical Metal Sausages",
        "count": 80
    }
]
```

Therefore, why not change the query to this?

```sql
SELECT p.name, s.name as size, s.count FROM products p JOIN s IN p.sizes WHERE s.count >= 75
```

Query result (included size name)

```json
[
    {
        "name": "Practical Metal Sausages",
        "size": "Medium",
        "count": 96
    },
    {
        "name": "Practical Metal Sausages",
        "size": "Large",
        "count": 80
    }
]
```

**Comment by markjbrown** [comment]
This was updated some time ago but did not mark issue as closed. Closing now.
